name: docs_pages_workflow
 
# execute this workflow automatically when a we push to master
on:
  push:
    branches: 
      - main
      - develop
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
 
      - name: Install dependencies
        run: |
          python -m pip install -U sphinx
          python -m pip install sphinx-rtd-theme
          # python -m pip install sphinxcontrib-apidoc
          python -m pip install sphinx-autoapi
      - name: Clean previous build
        run: rm -rf docs/_build/
  

      - name: make the sphinx docs
        run: sphinx-build -b html docs/source docs/build/html

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "skosar2@uic.edu"
          git config --local user.name "skosar2"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
